name: Build + Push ooNodz image

on:
  push:
    branches:
      - aylin
      - main
    tags:
      - "*"

defaults:
  run:
    shell: bash

jobs:
  build_oonodz_fuji_image_aylin:
    name: Build Docker Image
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Current Tag
        id: get_tag
        run: echo ::set-output name=tag::$(git describe --abbrev=0 --tags)

      - name: Login to Docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASS }} 

      - name: Build Dockerfile and Push it
        run: |
          TAG_FUJI=""
          
          if [ "$CURRENT_BRANCH" == "aylin" ]; then
            TAG_FUJI="fuji-"
            echo "COPY --from=builder /build/jvrKsTB9MfYGnAXtxbzFYpXKceXr9J8J8ej6uWGrYM5tXswhJ /root/.avalanchego/plugins/jvrKsTB9MfYGnAXtxbzFYpXKceXr9J8J8ej6uWGrYM5tXswhJ" >> Dockerfile
          fi

          if [ -n "$GITHUB_TAG" ]; then
            TAG_END=$GITHUB_TAG
          else
            TAG_END=$GITHUB_SHA
          fi

          export BUILD_IMAGE_ID="${{ vars.AVALANCHE_VERSION }}-${TAG_FUJI}${TAG_END}"

          ./scripts/build_image.sh
        env:
          CURRENT_BRANCH: ${{ github.head_ref || github.ref_name }} 
          PUSH_DOCKER_IMAGE: true 
          DOCKERHUB_REPO: logisticx/ava
          GITHUB_TAG: ${{ steps.get_tag.outputs.tag }}
          GITHUB_SHA: ${{ github.sha }}
